"""Type stubs for the Bloomberg Desktop API Python package (blpapi 3.26.x).

Only the surface consumed by the native adapter is declared. Verified against
the installed package (SPEC §5.1): method names mirror ``blpapi`` exactly.
"""

from collections.abc import Callable, Iterator
from typing import Any

class Name:
    def __init__(self, nameString: str | None, internalHandle: Any = None) -> None: ...
    @staticmethod
    def findName(nameString: str) -> Name | None: ...
    @staticmethod
    def hasName(nameString: str) -> bool: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DataType:
    BOOL: int
    BYTE: int
    BYTEARRAY: int
    CHAR: int
    CHOICE: int
    CORRELATION_ID: int
    DATE: int
    DATETIME: int
    DECIMAL: int
    ENUMERATION: int
    FLOAT32: int
    FLOAT64: int
    INT32: int
    INT64: int
    SEQUENCE: int
    STRING: int
    TIME: int

class CorrelationId:
    INT_TYPE: int
    OBJECT_TYPE: int
    AUTOGEN_TYPE: int
    UNSET_TYPE: int
    def __init__(self, value: Any = None, classId: int = 0) -> None: ...
    def value(self) -> Any: ...
    def type(self) -> int: ...
    def classId(self) -> int: ...

class Element:
    def name(self) -> Name: ...
    def datatype(self) -> int: ...
    def numValues(self) -> int: ...
    def numElements(self) -> int: ...
    def isArray(self) -> bool: ...
    def isComplexType(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isNullValue(self, index: int = 0) -> bool: ...
    def getElement(self, index_or_name: int | str | Name) -> Element: ...
    def hasElement(self, name: str | Name) -> bool: ...
    def getValueAsBool(self, index: int = 0) -> bool: ...
    def getValueAsInteger(self, index: int = 0) -> int: ...
    def getValueAsFloat(self, index: int = 0) -> float: ...
    def getValueAsString(self, index: int = 0) -> str: ...
    def getValueAsBytes(self, index: int = 0) -> bytes: ...
    def getValueAsDatetime(self, index: int = 0) -> Any: ...
    def getValueAsName(self, index: int = 0) -> Name: ...
    def getValueAsElement(self, index: int = 0) -> Element: ...
    def getChoice(self) -> Element: ...
    def setChoice(self, name: str | Name) -> Element: ...
    def setValue(self, value: Any) -> None: ...
    def appendValue(self, value: Any) -> None: ...
    def appendElement(self) -> Element: ...
    def setElement(self, name: str | Name, value: Any) -> None: ...

class Message:
    def messageType(self) -> Name: ...
    def asElement(self) -> Element: ...
    def correlationIds(self) -> list[CorrelationId]: ...
    def correlationId(self, index: int = 0) -> CorrelationId: ...
    def topicName(self) -> str: ...
    def service(self) -> Any: ...
    def numElements(self) -> int: ...

class Event:
    ADMIN: int
    AUTHORIZATION_STATUS: int
    PARTIAL_RESPONSE: int
    REQUEST: int
    REQUEST_STATUS: int
    RESOLUTION_STATUS: int
    RESPONSE: int
    SERVICE_STATUS: int
    SESSION_STATUS: int
    SUBSCRIPTION_DATA: int
    SUBSCRIPTION_STATUS: int
    TIMEOUT: int
    TOKEN_STATUS: int
    TOPIC_STATUS: int
    UNKNOWN: int
    def eventType(self) -> int: ...
    def __iter__(self) -> Iterator[Message]: ...

class EventQueue:
    def nextEvent(self, timeout: int = 0) -> Event: ...
    def tryNextEvent(self) -> Event | None: ...
    def purge(self) -> None: ...

class Constant:
    def name(self) -> Name: ...
    def datatype(self) -> int: ...
    def getValueAsString(self) -> str: ...
    def status(self) -> int: ...

class ConstantList:
    def numConstants(self) -> int: ...
    def getConstantAt(self, index: int) -> Constant: ...
    def getConstant(self, name: str | Name) -> Constant: ...
    def hasConstant(self, name: str | Name) -> bool: ...
    def name(self) -> Name: ...
    def datatype(self) -> int: ...

class SchemaTypeDefinition:
    DEPRECATED: int
    ACTIVE: int
    def name(self) -> Name: ...
    def description(self) -> str: ...
    def datatype(self) -> int: ...
    def status(self) -> int: ...
    def isComplexType(self) -> bool: ...
    def isSimpleType(self) -> bool: ...
    def isEnumerationType(self) -> bool: ...
    def numElementDefinitions(self) -> int: ...
    def getElementDefinition(self, index_or_name: int | str | Name) -> SchemaElementDefinition: ...
    def hasElementDefinition(self, name: str | Name) -> bool: ...
    def elementDefinitions(self) -> list[SchemaElementDefinition]: ...
    def enumeration(self) -> ConstantList: ...

class SchemaElementDefinition:
    UNBOUNDED: int
    DEPRECATED: int
    ACTIVE: int
    def name(self) -> Name: ...
    def alternateNames(self) -> list[Name]: ...
    def description(self) -> str: ...
    def status(self) -> int: ...
    def datatype(self) -> int: ...
    def minValues(self) -> int: ...
    def maxValues(self) -> int: ...
    def typeDefinition(self) -> SchemaTypeDefinition: ...

class Operation:
    def name(self) -> Name: ...
    def description(self) -> str: ...
    def requestDefinition(self) -> SchemaElementDefinition: ...
    def numResponseDefinitions(self) -> int: ...
    def getResponseDefinitionAt(self, index: int) -> SchemaElementDefinition: ...
    def responseDefinitions(self) -> list[SchemaElementDefinition]: ...

class Service:
    def name(self) -> Name: ...
    def description(self) -> str: ...
    def numOperations(self) -> int: ...
    def operations(self) -> list[Operation]: ...
    def getOperation(self, name: str | Name) -> Operation: ...
    def hasOperation(self, name: str | Name) -> bool: ...
    def createRequest(self, operation: str | Name) -> Request: ...
    def authorizationServiceName(self) -> str: ...

class Request:
    def getElement(self, name: str | Name) -> Element: ...
    def set(self, name: str | Name, value: Any) -> None: ...
    def append(self, name: str | Name, value: Any) -> None: ...

class SubscriptionList:
    def __init__(self) -> None: ...
    def add(
        self,
        topic: str | None,
        fields: str | list[str] | None = None,
        options: str | list[str] | dict[str, Any] | None = None,
        correlationId: CorrelationId | None = None,
    ) -> int: ...
    def clear(self) -> int: ...
    def size(self) -> int: ...
    def correlationIdAt(self, index: int) -> CorrelationId: ...
    def topicStringAt(self, index: int) -> str: ...

class SessionOptions:
    AUTO: int
    DAPI: int
    SAPI: int
    def __init__(self) -> None: ...
    def setServerHost(self, host: str) -> None: ...
    def setServerPort(self, port: int) -> None: ...
    def setServerAddress(self, host: str, port: int, index: int) -> None: ...
    def setConnectTimeout(self, timeoutMilliseconds: int) -> None: ...
    def setDefaultSubscriptionService(self, service: str) -> None: ...
    def setDefaultTopicPrefix(self, prefix: str) -> None: ...
    def setMaxPendingRequests(self, maxPendingRequests: int) -> None: ...
    def setAuthenticationOptions(self, options: str) -> None: ...
    def setNumStartAttempts(self, numAttempts: int) -> None: ...
    def setAutoRestartOnDisconnection(self, flag: bool) -> None: ...

class Session:
    def __init__(
        self,
        options: SessionOptions | None = None,
        eventHandler: Callable[[Event, Session], None] | None = None,
        eventDispatcher: Any = None,
    ) -> None: ...
    def start(self) -> bool: ...
    def startAsync(self) -> None: ...
    def stop(self) -> None: ...
    def stopAsync(self) -> None: ...
    def openService(self, serviceName: str) -> bool: ...
    def openServiceAsync(self, serviceName: str, correlationId: CorrelationId | None = None) -> CorrelationId: ...
    def getService(self, serviceName: str) -> Service: ...
    def sendRequest(
        self,
        request: Request,
        identity: Any = None,
        correlationId: CorrelationId | None = None,
        eventQueue: EventQueue | None = None,
        requestLabel: str | None = None,
    ) -> CorrelationId: ...
    def cancel(self, correlationId: CorrelationId | list[CorrelationId] | None) -> None: ...
    def subscribe(
        self,
        subscriptionList: SubscriptionList,
        identity: Any = None,
        requestLabel: str | None = None,
        mode: Any = ...,
    ) -> list[Any] | None: ...
    def resubscribe(
        self,
        subscriptionList: SubscriptionList,
        requestLabel: str | None = None,
        resubscriptionId: int | None = None,
        mode: Any = ...,
    ) -> list[Any] | None: ...
    def unsubscribe(self, subscriptionList: SubscriptionList) -> None: ...
    def nextEvent(self, timeout: int = 0) -> Event: ...
    def tryNextEvent(self) -> Event | None: ...
    def isValid(self) -> bool: ...
